version: "3.9"

services:
  ansiblenodectl:
    build: "./ubuntu"
    image: ansible-lab:latest
    container_name: "ansiblenodectl"
    hostname: "ansiblenodectl"
    ports:
      - "2020:22"
    restart: always
    networks:
      ansible:
        ipv4_address: "10.18.0.10"

  ansiblenode1:
    image: ansible-lab:latest
    build: "./ubuntu"
    container_name: "ansiblenode1"
    hostname: "ansiblenode1"
#    ports:
#      - "2021:22"
    restart: always
    networks:
      ansible:
#        ipv4_address: "10.18.0.11"

  ansiblenode2:
    image: ansible-lab:latest
    build: "./ubuntu"
    container_name: "ansiblenode2"
    hostname: "ansiblenode2"
#    ports:
#      - "2022:22"
    restart: always
    networks:
      ansible:
#        ipv4_address: "10.18.0.13"

  ansiblenode3:
    image: ansible-lab:latest
    build: "./ubuntu"
    container_name: "ansiblenode3"
    hostname: "ansiblenode3"
#    ports:
#      - "2023:22"
    restart: always
    networks:
      ansible:
#        ipv4_address: "10.18.0.13"      
networks:
  ansible:
    ipam:
      config:
        - subnet: 10.18.0.0/16
          gateway: 10.18.0.1
